-- Baseline schema. This mirrors the tables that Hibernate's ddl-auto=update
-- had already created before Flyway was introduced. On databases that already
-- have these tables, Flyway marks this version as done via
-- spring.flyway.baseline-on-migrate instead of re-running it (see
-- application.yml). Only a brand new, empty database actually executes this
-- script.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    role varchar(255) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('STUDENT', 'ORGANIZER', 'ADMIN'))
);

CREATE TABLE clubs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description text,
    contact_email varchar(255),
    logo_url varchar(255),
    organizer_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uk_clubs_organizer_id UNIQUE (organizer_id),
    CONSTRAINT fk_clubs_organizer FOREIGN KEY (organizer_id) REFERENCES users(id)
);

CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    description text NOT NULL,
    event_date date NOT NULL,
    start_time time(0) NOT NULL,
    end_time time(0) NOT NULL,
    location varchar(255) NOT NULL,
    capacity integer NOT NULL,
    category varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    rejection_reason varchar(255),
    banner_url varchar(255),
    organizer_id bigint NOT NULL,
    club_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT fk_events_organizer FOREIGN KEY (organizer_id) REFERENCES users(id),
    CONSTRAINT fk_events_club FOREIGN KEY (club_id) REFERENCES clubs(id),
    CONSTRAINT events_category_check CHECK (category IN ('TECHNICAL', 'CULTURAL', 'SPORTS', 'WORKSHOP', 'SEMINAR', 'SOCIAL', 'CAREER', 'OTHER')),
    CONSTRAINT events_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED'))
);

CREATE TABLE registrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL,
    student_id bigint NOT NULL,
    registered_at timestamp(6) NOT NULL,
    CONSTRAINT uk_registrations_student_event UNIQUE (student_id, event_id),
    CONSTRAINT fk_registrations_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_registrations_student FOREIGN KEY (student_id) REFERENCES users(id)
);

CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    expires_at timestamp(6) NOT NULL,
    revoked boolean NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE password_reset_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    expires_at timestamp(6) NOT NULL,
    used boolean NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);
